// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrganization struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Logo        *string `json:"logo"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Organization struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Logo        *string `json:"logo"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UpdateOrganization struct {
	ID          string  `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Logo        *string `json:"logo"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
