// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewOrganization struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Logo        *string `json:"logo"`
}

type NewUser struct {
	Username string  `json:"username"`
	Name     string  `json:"name"`
	Picture  *string `json:"picture"`
	Role     string  `json:"role"`
	Provider string  `json:"provider"`
	TokenID  string  `json:"tokenID"`
	Status   string  `json:"status"`
}

type Organization struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Logo        *string `json:"logo"`
}

type UpdateOrganization struct {
	ID          string  `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Logo        *string `json:"logo"`
}

type UpdateUser struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Name     string  `json:"name"`
	Picture  *string `json:"picture"`
	Role     string  `json:"role"`
	Provider string  `json:"provider"`
	TokenID  string  `json:"tokenID"`
	Status   string  `json:"status"`
}

type User struct {
	ID         string    `json:"id"`
	Username   string    `json:"username"`
	Name       string    `json:"name"`
	Picture    *string   `json:"picture"`
	Role       string    `json:"role"`
	Provider   string    `json:"provider"`
	TokenID    string    `json:"tokenID"`
	CreateDate time.Time `json:"createDate"`
	UpdateDate time.Time `json:"updateDate"`
	Status     string    `json:"status"`
}
